INSERT INTO public.segmento (id,descricao) VALUES
	(1,'Alimentício'),
	(2,'Automotivo'),
	(3,'Tecnologia'),
	(4,'Educação'),
	(5,'Construção Civil'),
	(6,'Agronegócio'),
	(7,'Financeiro'),
	(8,'Varejo'),
	(9,'Atacado'),
	(10,'Saúde'),
	(11,'Farmacêutico'),
	(12,'Imobiliário'),
	(13,'Comunicação'),
	(14,'Publicidade e Marketing'),
	(15,'Consultoria'),
	(16,'Jurídico'),
	(17,'Contábil'),
	(18,'Turismo'),
	(19,'Hotelaria'),
	(20,'Logística'),
	(21,'Transporte'),
	(22,'Moda e Vestuário'),
	(23,'Calçados e Acessórios'),
	(24,'Beleza e Estética'),
	(25,'Energia'),
	(26,'Petroquímico'),
	(27,'Siderúrgico'),
	(28,'Metalúrgico'),
	(29,'Mineração'),
	(30,'Telecomunicações'),
	(31,'Entretenimento'),
	(32,'Esportes e Lazer'),
	(33,'Serviços Gerais'),
	(34,'Serviços Domésticos'),
	(35,'Segurança Patrimonial'),
	(36,'Seguros'),
	(37,'Artesanato'),
	(38,'Pesca'),
	(39,'Pecuária'),
	(40,'TI e Software'),
	(41,'E-commerce'),
	(42,'Eventos'),
	(43,'Arquitetura e Urbanismo'),
	(44,'Design de Interiores'),
	(45,'Engenharia'),
	(46,'Ambiental'),
	(47,'Reciclagem'),
	(48,'Manufatura'),
	(49,'Importação e Exportação'),
	(50,'Startups');
