INSERT INTO public.personalidade (id,descricao) VALUES
	 (1,'Aventureiro'),
	 (2,'Calmo'),
	 (3,'Analítico'),
	 (4,'Criativo'),
	 (5,'Sociável'),
	 (6,'Introvertido'),
	 (7,'Determinando'),
	 (8,'Organizado'),
	 (9,'Desorganizado'),
	 (10,'Realista');
INSERT INTO public.personalidade (id,descricao) VALUES
	 (11,'Idealista'),
	 (12,'Pragmático'),
	 (13,'Empreendedor'),
	 (14,'Reservado'),
	 (15,'Empático'),
	 (16,'Impulsivo'),
	 (17,'Cauteloso'),
	 (18,'Engraçado'),
	 (19,'Sério'),
	 (20,'Proativo');
INSERT INTO public.personalidade (id,descricao) VALUES
	 (21,'Romântico'),
	 (22,'Independente'),
	 (23,'Leal'),
	 (24,'Curioso'),
	 (25,'Metódico'),
	 (26,'Competitivo'),
	 (27,'Colaborativo'),
	 (28,'Sensível'),
	 (29,'Objetivo'),
	 (30,'Apreciador de arte');
INSERT INTO public.personalidade (id,descricao) VALUES
	 (31,'Apreciador de música'),
	 (32,'Amante da natureza'),
	 (33,'Apaixonado por tecnologia'),
	 (34,'Esportista'),
	 (35,'Leitor assíduo'),
	 (36,'Cinéfilo'),
	 (37,'Gamer'),
	 (38,'Minimalista'),
	 (39,'Consumista'),
	 (40,'Espiritualista');
INSERT INTO public.personalidade (id,descricao) VALUES
	 (41,'Racional'),
	 (42,'Sonhador'),
	 (43,'Visionário'),
	 (44,'Apreciador de café'),
	 (45,'Amante de animais'),
	 (46,'Vegetariano'),
	 (47,'Vegan'),
	 (48,'Trabalhador noturno'),
	 (49,'Matutino'),
	 (50,'Ligado à família');
