services:
  db:
    image: postgres:15
    container_name: luci-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - "${DB_PORT}:5432"
    networks:
      - luci-network

  redis:
        image: redis:7.4-alpine
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - luci-network
    
networks:
  luci-network:
    driver: bridge

volumes:
  postgres_data: